root: true
parser: '@typescript-eslint/parser'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended
plugins:
  - '@typescript-eslint'
  - react-hooks
